### ISSUE TITLE
category with 2 words url problems

### ISSUE THREAD

**Issue by rdyar** [jekyll/jekyll-help#129]
I am defining:
category: abc xyz
in the post front matter.

Then I have the permalink in the _config file as:
permalink: /:categories/:title/

when the site generates I get a url that has spaces in it.

Is it possible to have the space in the category replaced with a dash in the url?

This is breaking when I upload to Amazon S3.

**Comment by pamgriffith** [comment]
Is there any progress on this? I, too, would like to have multi-word categories and no spaces in my urls. I will try the plugin, but this seems like it should be a core feature, as I believe spaces in URLs are supposed to be percent encoded (both by the RFC referenced above, which specifically calls them out as "unsafe" and [rfc3986](http://tools.ietf.org/html/rfc3986), which updates it).

**Comment by fusilli** [comment]
I think I came up with a simple workaround for this (and also for getting rid of special characters - as mentioned in [this topic](https://github.com/jekyll/jekyll/issues/782)).

Let's say you want to have categories "recenzje książek" and "recenzje filmów" (_book_ and _movie reviews_ in Polish respectively). Both of these are two word categories with special Polish characters.

In your post metadata you use category names already cleaned up (dashes instead of spaces, no special characters):

```
category: recenzje-ksiazek
```

or

```
category: recenzje-filmow
```

Then you create **categories.yml** file in your **_data** directory containing

```
- name: Recenzje książek
  slug: recenzje-ksiazek
- name: Recenzje filmów
  slug: recenzje-filmow
```

In your site templates instead of

```
{{ post.category }}
```

you put

```
{% for category in site.data.categories %}{% if post.category == category.slug %}{{ category.name }}{% endif %}{% endfor %}
```

This way you have spaces and special characters visible on your site (+ Title Case if you want), but keep dashes, no special characters and lower case in the urls.

**Comment by jaybe-jekyll** [comment]
Enjoyed reading and learning about your approach. Thanks! Nifty! :dancer:

**Comment by jfi** [comment]
+1 for @djacquel's approach, works well. Wish it didn't have to be a plugin though...

**Comment by llbbl** [comment]
+1 for @djacquel's approach, works well. Wish it didn't have to be a plugin though...

**Comment by parkr** [comment]
This repository is no longer maintained. If you're still experiencing this problem, please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
