### ISSUE TITLE
Jekyll not compiling site on localhost:8000

### ISSUE THREAD

**Issue by mloderme** [jekyll/jekyll-help#184]
Hello,

I have Jekyll 2.4.0 and Ruby 2.0.09576 installed.

I am working along with Travis from YouTube channel 'DevTips' and using all of his files/information to compile his 'Artist' project site. Last week I successfully served the project site via Ruby/Jekyll serve from source folder. Today, I tried the same process and the site would not compile. I am using same localhost:8000, that is verified. I am running Win7 64bit and followed advice to run UTF-8 encoding command: chcp 65001.

No files have changed in the portfolio folder on my PC. The other thing on jekyllrb.com/windows/ says is to add a line of code for 'Auto-regeneration' to the 'Gemfile'...OK, it does not say where this 'Gemfile' is to edit...is it here?: C:.../RubyDevKit/bin/gem.windows batch file?

I am stumped as to why the project files compiled and displayed just fine last week and today it does not work, NO connection can be made to localhost:8000...so no site generated. I also tried to view view site via Prepros, using their 'Open Live Preview' and that generates a site on localhost:8001 displaying only this text: --- --- {% include header.html %} {% include about.html %} {% include work.html %} {% include clients.html %} {% include contact.html %} {% include form.html %} {% include footer.html %} 

Any ideas?

Thank you!
Mark

**Comment by TysonGerber** [comment]
Mark, 
I am sorry this is YEARS late however, I just found Travis about a month ago and hope this will help anyone in the future that has the same troubles. Travis put a README file in his Artists-Theme section. 

Here are the instructions:

 ## How to install/use

In order to get this super fantastic [Jekyll](http://jekyllrb.com) powered template for Artists follow this simple step:

* If you haven't got ruby installed on your computer, install it.
* Then run in your terminal `$ gem install jekyll`
* Move/`cd` to a folder, always in your terminal, in which you want to insert the *Artists-Theme*
* Run `git clone https://github.com/DevTips/Artists-Theme.git`
* Then `cd Artists-Theme`
* `jekyll serve --watch`
* **DONE**


A couple other commands I had to run in my terminal were:

- sudo gem install bundler
- bundle exec jekyll serve

Watch this youtube video, you should only have to watch to 5 mins. https://www.youtube.com/watch?v=iWowJBRMtpc

Hope this helps all the future peeps!
