### ISSUE TITLE
Copy files verbatim to destination, without processing

### ISSUE THREAD

**Issue by clauswilke** [jekyll/jekyll-help#214]
There should be an option that tells Jekyll to copy files verbatim, without processing. At present, to my knowledge, there is no way that one can host a markdown file verbatim. This [stackoverflow post](http://stackoverflow.com/questions/20509912/how-to-post-an-md-file-on-jekyll-website) suggests that one could host markdown files that don't have YAML front-matter, but that doesn't help when I want to host files that actually do contain such front-matter.

A simple configuration option like this:
`verbatim: [DIR, FILE, ...]`
modeled after `exclude` and `include`, would do the trick.

**Comment by troyswanson** [comment]
I haven't tested this, so I don't know if this would actually work, but try using a `txt` file extension instead of `md` or `markdown`. I believe Jekyll converts files based on their file extension, so if you give it a `txt`, it won't have a converter for it and just dump it as it sees it.

Let me know if that works. I'm curious, now.

**Comment by clauswilke** [comment]
File extensions don't matter, as far as I can tell. I have files ending in .Rmd, which should be ignored, but they are not.

**Comment by parkr** [comment]
This repository is no longer maintained. If you're still experiencing this problem, please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
