### ISSUE TITLE
{% raw %} {% endraw %} tags not being respected

### ISSUE THREAD

**Issue by holidayroman** [jekyll/jekyll-help#40]
I can't figure this out - for some reason the stuff I put inside of {%raw%}{%endraw%} tags is still being parsed/evaluated by Liquid.

So if I make a .md file with just this for content:

```
Start
{% raw %}
{{something}}
{% endraw %}
End
```

My generated HTML just looks like:
Start
End

Same goes for:

```
Start
{% raw %}
{% sometag %}
{% endraw %}
End
```

If sometag is a real tag, then Liquid evaluates it and replaces it with whatever that tag gets replaced with, and if it's not then jekyll build tells me it doesn't know that the tag 'something'

Been stuck on this for a while and really can't figure it out.

**_config.yml:**
encoding: utf-8
markdown: redcarpet 
highlighter: highlighter 
redcarpet:
  extensions: ['highlight','strikethrough']
...

**relevant gem versions:**
jekyll 2.0.2
liquid 2.5.5
kramdown 1.3.3
redcarpet 3.1.1

**Comment by qwertie** [comment]
At some point in 2017 it became illegal to write `{% raw %}` at the beginning (after front-matter) and `{% endraw %}` at the end of a file. But this only occurs with Jekyll 3.5.2 on GitHub, not the Jekyll 3.5.2 that I installed on my local machine.

I had to change a whole bunch of files in [my GH pages site](https://github.com/qwertie/loyc.net/commits/gh-pages) because I kept getting emails saying 

    The tag `raw` on line 1 in `filename.md/#excerpt` was not properly closed.

**Comment by ashmaroli** [comment]
@qwertie this repo is no longer being maintained.
