### ISSUE TITLE
Creating static pages from markdown and evaluating liquid tags.

### ISSUE THREAD

**Issue by holidayroman** [jekyll/jekyll-help#51]
So I'd like to be able to create static pages from a markdown file in the same way I'd make a blog post from a markdown file, but I can't figure out a way to get jekyll to render liquid content in any markdown file that isn't in  _posts/

Is this even possible? I mean I suppose I could put my page in posts and handle the case with something hacky, but I'd really like to be able to generate my site/about page from liquid tags laden markdown.

So far I've got this. It evaluates the markdown content but totally ignores the liquid tags.

_includes/about.md

```

---
title: about

---
La La La
{%some liquid tag%}
```

and in about.html

```

---
layout: layout

---

{% capture about %}{% include about.md %}{% endcapture %}
{{ about  | markdownify }}
```

My output in the site/about page is just:

La La La

**Comment by duanefields** [comment]
Can you explain what the resolution was? I have having the same question....

**Comment by greenify** [comment]
Hi @duanefields,

I recently encountered a similar problem when I wanted to include projects which are independent jekyll pages on [a summary page](http://biojs.net/gsoc/2015/).

My ideas were
* `include_relative` (problem: one [can't include pages with a YAML front matter](https://github.com/jekyll/jekyll/issues/3476))
* picking the page from all pages (problem: liquid tags are not evaluated)

As I needed to get this working for github pages (=`without plugins`), my workaround is a combination of both and looks horrible - I would be very happy if this gets fixed in a future release and there is an easier way to include a jekyll page in another jekyll page :)

Basically it loops over all pages, picks the one I want to include, uses their filePath to call `include_relative` and then strips the YAML front matter.

```
{% for p in include.pages %}
 {% if p.gsoc == include.gsocYear %}

 {% capture inpath %}{{page.gsocYear}}/projects/{{ p.name }}{% endcapture %}

 {% capture content %}{% include_relative {{inpath}} %}{% endcapture %}

<!-- probably the ugliest way to remove the YAML front matter -->
{% assign lines = content | newline_to_br | split: "<br />" %}

{% assign newContent = "" %}
{% for l in lines %}
    {% if forloop.index >= 6 %}
		{% assign newContent  = newContent | append: l %}
	{% endif %}
{% endfor %}
{{ newContent | markdownify }}
```

source: https://github.com/biojs/biojs.net/blob/gh-pages/gsoc/includes/ideas.md
page: http://biojs.net/gsoc/2015/
