### ISSUE TITLE
Jekyll 2.1.0 search plugin that supports Collections

### ISSUE THREAD

**Issue by AJ-Acevedo** [jekyll/jekyll-help#92]
Has anyone found a good search plugin for Jekyll 2.1.0 that will support Collections?

Looks like [jekyll-lunr-js-search](https://github.com/slashdotdash/jekyll-lunr-js-search/issues/28) wont be supporting Collections.

**Comment by iloveip** [comment]
@AJ-Acevedo Did you find any solution for this? I'm also looking for a search plugin which powers Jekyll Collections now.

**Comment by AJ-Acevedo** [comment]
Nope there is still a $65 bounty for this

[![Bountysource](https://www.bountysource.com/badge/issue?issue_id=2074457)](https://www.bountysource.com/issues/2074457-new-jekyll-collections?utm_source=2074457&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by mhulse** [comment]
@iloveip and @AJ-Acevedo, why don't one of you post an example of the JSON output you want to search? Again, most search plugins I've seen just loop over json to search, they don't care about Jekyll's "Collections".

Suggestion: Rather than worry about the search plugin supporting "Collections", worry about the plugin supporting nested structures. Unless I'm mistaken, that's really what you need.

I personally would like to see an example JSON output that you would like to have searched. Can one of you post an example?

**Comment by kojoru** [comment]
Just letting you know that we've successfully merged collection support into `jekyll-junr-js-search`. Try it and see.

**Comment by parkr** [comment]
This repository is no longer maintained. If you're still experiencing this problem, please search for your issue on [Jekyll Talk](https://talk.jekyllrb.com/), our new community forum. If it isn't there, feel free to post to the Help category and someone will assist you. Thanks!
